
package operacionesimgmvc;
import java.awt.Color;

/**
 *
 * @author Josue Parrado
 */
public class Calculadora extends javax.swing.JFrame {

    double valor1;
    double valor2;
    Complejo A,B,C;
    int codigo;
    
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnSuma = new javax.swing.JButton();
        TxtDisplay = new javax.swing.JTextField();
        BtnResta = new javax.swing.JButton();
        BtnMulti = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnDividir = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnImaginario = new javax.swing.JButton();
        BtnReal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculadora.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        BtnSuma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnSuma.setText("+");
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });
        BtnSuma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSumaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BtnSumaKeyTyped(evt);
            }
        });

        TxtDisplay.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        TxtDisplay.setForeground(new java.awt.Color(153, 153, 153));
        TxtDisplay.setText("Ingrese la parte real y luego la parte imaginaria");
        TxtDisplay.setCaretColor(new java.awt.Color(102, 102, 102));
        TxtDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtDisplayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TxtDisplayMouseReleased(evt);
            }
        });
        TxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDisplayActionPerformed(evt);
            }
        });

        BtnResta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnResta.setText("-");
        BtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestaActionPerformed(evt);
            }
        });

        BtnMulti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnMulti.setText("*");
        BtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiActionPerformed(evt);
            }
        });

        BtnIgual.setText("=");
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        BtnDividir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnDividir.setText("/");
        BtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDividirActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("CE");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnImaginario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnImaginario.setText("Imaginario");
        BtnImaginario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImaginarioActionPerformed(evt);
            }
        });

        BtnReal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnReal.setText("Real");
        BtnReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ImagenLayout = new javax.swing.GroupLayout(Imagen);
        Imagen.setLayout(ImagenLayout);
        ImagenLayout.setHorizontalGroup(
            ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagenLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ImagenLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ImagenLayout.createSequentialGroup()
                            .addGroup(ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagenLayout.createSequentialGroup()
                                        .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))
                                    .addGroup(ImagenLayout.createSequentialGroup()
                                        .addComponent(BtnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagenLayout.createSequentialGroup()
                                    .addComponent(BtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BtnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)))
                            .addGroup(ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnImaginario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnReal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
        );
        ImagenLayout.setVerticalGroup(
            ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ImagenLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ImagenLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(BtnReal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnImaginario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
        A=new Complejo(B);
        TxtDisplay.setText(null);
        BtnImaginario.setEnabled(true);
        BtnReal.setEnabled(true);
        TxtDisplay.requestFocus();
        codigo=1;
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void TxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDisplayActionPerformed

    private void BtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestaActionPerformed
        A=new Complejo(B);
        TxtDisplay.setText(null);
        BtnImaginario.setEnabled(true);
        BtnReal.setEnabled(true);
        TxtDisplay.requestFocus();
        codigo=2;
    }//GEN-LAST:event_BtnRestaActionPerformed

    private void BtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiActionPerformed
        A=new Complejo(B);
        TxtDisplay.setText(null);
        BtnImaginario.setEnabled(true);
        BtnReal.setEnabled(true);
        TxtDisplay.requestFocus();
        codigo=3;
    }//GEN-LAST:event_BtnMultiActionPerformed

    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        switch(codigo){
            case 1:
            {
                B=A.sumar(B);
                break;
            }
            case 2:
            {
                B=A.restar(B);
                break;
            }
            case 3:
            {
                B=A.multiplicar(B);
                break;
            }
            case 4:
            {
                B=A.dividir(B);
                break;
            }
        }
        TxtDisplay.setText(B.salida());
    }//GEN-LAST:event_BtnIgualActionPerformed

    private void BtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDividirActionPerformed
        A=new Complejo(B);
        TxtDisplay.setText(null);
        BtnImaginario.setEnabled(true);
        BtnReal.setEnabled(true);
        TxtDisplay.requestFocus();
        codigo=4;
    }//GEN-LAST:event_BtnDividirActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        TxtDisplay.setText(null);
        BtnImaginario.setEnabled(true);
        BtnReal.setEnabled(true);
        TxtDisplay.requestFocus();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRealActionPerformed
        valor1=Double.parseDouble(TxtDisplay.getText());
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        BtnReal.setEnabled(false);
    }//GEN-LAST:event_BtnRealActionPerformed

    private void BtnImaginarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImaginarioActionPerformed
        valor2=Double.parseDouble(TxtDisplay.getText());
        B = new Complejo(valor1,valor2);
        TxtDisplay.setText(B.salida());
        TxtDisplay.setText(null);
        TxtDisplay.requestFocus();
        BtnImaginario.setEnabled(false);
    }//GEN-LAST:event_BtnImaginarioActionPerformed

    private void TxtDisplayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtDisplayMousePressed
        TxtDisplay.setText("");
        TxtDisplay.setForeground(Color.black);
    }//GEN-LAST:event_TxtDisplayMousePressed

    private void TxtDisplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtDisplayMouseReleased
        
    }//GEN-LAST:event_TxtDisplayMouseReleased

    private void BtnSumaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSumaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSumaKeyTyped

    private void BtnSumaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSumaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSumaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDividir;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnImaginario;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnMulti;
    private javax.swing.JButton BtnReal;
    private javax.swing.JButton BtnResta;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JPanel Imagen;
    private javax.swing.JTextField TxtDisplay;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
